baseurl: https://maxturgeon.ca/blog
languageCode: en-ca
title: Blog—Max Turgeon
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year-:month-:day-:slug/
menu:
  main:
    - name: Home
      url: https://maxturgeon.ca/
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: Where Max Turgeon blogs.
  favicon: icon.png
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Max Turgeon
    height: 50
    url: ../avatar.jpeg
    width: 50
